import React, { useState, useEffect } from 'react';
import Sidebar from './components/Sidebar';
import CalendarView from './components/CalendarView';
import GanttChart from './components/GanttChart';
import BulkGenerator from './components/BulkGenerator';
import PostsListView from './components/PostsListView';
import PostModal from './components/PostModal';
import MediaLibrary from './components/MediaLibrary';
import DesignStudios from './components/DesignStudios';
import LoginPage from './components/LoginPage';
import { Post, Campaign, Platform, MediaItem } from './types';
import * as api from './services/api';
import { useAuth } from './contexts/AuthContext';

const App: React.FC = () => {
  const { user, loading: authLoading, signOut, isConfigured } = useAuth();
  const [activeTab, setActiveTab] = useState('calendar');
  const [showBulkGen, setShowBulkGen] = useState(false);
  const [posts, setPosts] = useState<Post[]>([]);
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [mediaItems, setMediaItems] = useState<MediaItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);


  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingPost, setEditingPost] = useState<Post | null>(null);
  const [initialDate, setInitialDate] = useState<Date | undefined>(undefined);

  // Load data from Supabase on mount (or when user changes)
  useEffect(() => {
    // Don't fetch if still loading auth or no user when Supabase is configured
    if (isConfigured && (authLoading || !user)) {
      setIsLoading(false);
      return;
    }

    const fetchData = async () => {
      setIsLoading(true);
      try {
        const [fetchedPosts, fetchedCampaigns, fetchedMedia] = await Promise.all([
          api.getPosts(),
          api.getCampaigns(),
          api.getMediaItems()
        ]);
        setPosts(fetchedPosts);
        setCampaigns(fetchedCampaigns);
        setMediaItems(fetchedMedia);
      } catch (error) {
        console.error("Failed to fetch data:", error);
      } finally {
        setIsLoading(false);
      }
    };
    fetchData();
  }, [user, authLoading, isConfigured]);

  // Show login page if Supabase is configured but user is not logged in
  if (isConfigured && authLoading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-indigo-900 via-purple-900 to-pink-800 flex items-center justify-center">
        <div className="w-12 h-12 border-4 border-white/30 border-t-white rounded-full animate-spin"></div>
      </div>
    );
  }

  if (isConfigured && !user) {
    return <LoginPage />;
  }


  const handleBulkPosts = (newPosts: Post[]) => {
    // Save generated posts to DB one by one (or bulk insert if API supported it, here loop for simplicity)
    const savePromises = newPosts.map(p => api.createPost(p));

    Promise.all(savePromises).then((savedPosts) => {
      setPosts(prev => [...prev, ...savedPosts]);

      // If program, create campaign
      if (newPosts.length > 0 && newPosts[0].programId) {
        const prog = newPosts[0];
        const dates = newPosts.map(p => p.date.getTime());
        const minDate = new Date(Math.min(...dates));
        const maxDate = new Date(Math.max(...dates));

        const newCampaign: Campaign = {
          id: '', // Generated by DB
          name: prog.programName || 'برنامج جديد',
          startDate: minDate,
          endDate: maxDate,
          color: '#6366f1',
          description: `برنامج محتوى لـ ${prog.platform} (${newPosts.length} منشور)`
        };

        api.createCampaign(newCampaign).then(savedCampaign => {
          setCampaigns(prev => [savedCampaign, ...prev]);
        });
      }

      alert('تم حفظ البرنامج المولد في قاعدة البيانات بنجاح!');
    }).catch(e => {
      console.error("Failed to save bulk posts", e);
      alert('حدث خطأ أثناء حفظ المنشورات');
    });

    setShowBulkGen(false);
    setActiveTab('posts');
  };

  const deletePost = async (id: string) => {
    if (window.confirm('هل أنت متأكد من حذف هذا المنشور؟')) {
      try {
        await api.deletePost(id);
        setPosts(prev => prev.filter(p => p.id !== id));
      } catch (e) {
        console.error(e);
        alert('فشل الحذف');
      }
    }
  };

  const openNewPostModal = (date?: Date) => {
    setEditingPost(null);
    setInitialDate(date || new Date());
    setIsModalOpen(true);
  };

  const openEditPostModal = (post: Post) => {
    setEditingPost(post);
    setInitialDate(undefined);
    setIsModalOpen(true);
  };

  const handleSavePost = async (post: Post) => {
    try {
      if (post.id && posts.find(p => p.id === post.id)) {
        // Update
        await api.updatePost(post);
        setPosts(prev => prev.map(p => p.id === post.id ? post : p));
      } else {
        // Create (Clean ID if it was a temp local ID during creation, although createPost handles ignoring ID usually or payload doesn't send it if not needed)
        // Actually api.createPost generates new ID.
        // If we passed a dummy ID from modal initialization, api.createPost payload doesn't include ID so it works.
        const savedPost = await api.createPost(post);
        setPosts(prev => [...prev, savedPost]);
      }
      setIsModalOpen(false);
    } catch (e) {
      console.error("Failed to save post", e);
      alert('فشل حفظ المنشور');
    }
  };

  const handleUploadMedia = async (files: FileList) => {
    const file = files[0]; // Simple single file upload for now or loop for multiple
    if (!file) return;

    try {
      // Optimistic UI could be added here
      const savedItem = await api.uploadMediaItem(file);
      setMediaItems(prev => [savedItem, ...prev]);
    } catch (e) {
      console.error("Upload failed", e);
      alert('فشل رفع الملف. تأكد من إعداد Supabase Storage.');
    }
  };

  const handleDeleteMedia = async (id: string) => {
    const item = mediaItems.find(m => m.id === id);
    if (!item) return;

    if (window.confirm('حذف هذه الصورة؟')) {
      try {
        await api.deleteMediaItem(id, item.url);
        setMediaItems(prev => prev.filter(m => m.id !== id));
      } catch (e) {
        console.error(e);
        alert('فشل حذف الصورة');
      }
    }
  };

  // =====================
  // JSON EXPORT / IMPORT
  // =====================

  const handleExportPosts = () => {
    const exportData = {
      posts: posts.map(p => ({
        title: p.title,
        content: p.content,
        platform: p.platform,
        status: p.status,
        date: p.date.toISOString(),
        imageUrl: p.imageUrl || null,
        programId: p.programId || null,
        programName: p.programName || null
      })),
      exportedAt: new Date().toISOString(),
      totalPosts: posts.length
    };

    const blob = new Blob([JSON.stringify(exportData, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `socialflow-posts-${new Date().toISOString().slice(0, 10)}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleImportPosts = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = async (event) => {
      try {
        const json = JSON.parse(event.target?.result as string);

        if (!json.posts || !Array.isArray(json.posts)) {
          alert('تنسيق الملف غير صحيح. يجب أن يحتوي على مصفوفة "posts".');
          return;
        }

        const postsToImport: Post[] = json.posts.map((p: any, index: number) => ({
          id: '', // Will be generated by DB
          title: p.title || `منشور مستورد ${index + 1}`,
          content: p.content || '',
          platform: p.platform || Platform.INSTAGRAM,
          status: p.status || 'Draft',
          date: new Date(p.date || Date.now()),
          imageUrl: p.imageUrl || undefined,
          programId: p.programId || undefined,
          programName: p.programName || undefined
        }));

        // Confirm before importing
        if (!window.confirm(`سيتم استيراد ${postsToImport.length} منشور. هل تريد المتابعة؟`)) {
          return;
        }

        // Save to database
        const savePromises = postsToImport.map(p => api.createPost(p));
        const savedPosts = await Promise.all(savePromises);

        setPosts(prev => [...prev, ...savedPosts]);
        alert(`تم استيراد ${savedPosts.length} منشور بنجاح!`);

      } catch (err) {
        console.error(err);
        alert('فشل استيراد الملف. تأكد من صحة تنسيق JSON.');
      }
    };
    reader.readAsText(file);
    e.target.value = ''; // Reset input
  };


  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="flex h-64 items-center justify-center">
          <div className="text-gray-400 flex flex-col items-center">
            <div className="w-8 h-8 border-4 border-indigo-200 border-t-indigo-600 rounded-full animate-spin mb-2"></div>
            جاري تحميل البيانات...
          </div>
        </div>
      );
    }

    switch (activeTab) {
      case 'calendar':
        return (
          <div className="space-y-6">
            {showBulkGen && <BulkGenerator onPostsGenerated={handleBulkPosts} />}
            <CalendarView
              posts={posts}
              onAddPost={openNewPostModal}
              onEditPost={openEditPostModal}
            />
          </div>
        );
      case 'gantt':
        return <GanttChart campaigns={campaigns} />;
      case 'posts':
        return (
          <div className="space-y-6">
            {showBulkGen && <BulkGenerator onPostsGenerated={handleBulkPosts} />}
            <PostsListView posts={posts} onDeletePost={deletePost} onEditPost={openEditPostModal} />
          </div>
        );
      case 'media':
        return (
          <MediaLibrary
            mediaItems={mediaItems}
            onUpload={handleUploadMedia}
            onDelete={handleDeleteMedia}
          />
        );
      case 'studios':
        return <DesignStudios />;
      default:
        return <CalendarView posts={posts} onAddPost={openNewPostModal} onEditPost={openEditPostModal} />;
    }
  };

  return (
    <div className="min-h-screen flex bg-slate-50 font-['IBM_Plex_Sans_Arabic']">
      <Sidebar activeTab={activeTab} setActiveTab={(tab) => { setActiveTab(tab); setShowBulkGen(false); }} />
      <main className="flex-1 mr-64 p-8 transition-all">
        <header className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div>
            <h2 className="text-3xl font-bold text-gray-900 tracking-tight">
              {activeTab === 'calendar' && 'التقويم الذكي'}
              {activeTab === 'gantt' && 'تخطيط المحتوى'}
              {activeTab === 'posts' && 'أرشيف المحتوى'}
              {activeTab === 'media' && 'مكتبة الوسائط'}
              {activeTab === 'studios' && 'استديوهات التصميم'}
            </h2>
            <p className="text-gray-500 mt-1 font-medium text-sm">نظام إدارة المحتوى المتكامل (Supabase Edition)</p>
          </div>
          <div className="flex items-center gap-4">
            {/* User Info */}
            {user && (
              <div className="flex items-center gap-3 bg-white px-4 py-2 rounded-xl border border-gray-200">
                <div className="w-8 h-8 bg-indigo-100 rounded-full flex items-center justify-center text-indigo-600 font-bold text-sm">
                  {user.email?.charAt(0).toUpperCase()}
                </div>
                <div className="hidden md:block">
                  <p className="text-xs text-gray-500">مرحباً</p>
                  <p className="text-sm font-medium text-gray-700 max-w-[150px] truncate">{user.email}</p>
                </div>
                <button
                  onClick={signOut}
                  className="p-2 text-gray-400 hover:text-red-500 transition-colors"
                  title="تسجيل الخروج"
                >
                  <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4" /><polyline points="16 17 21 12 16 7" /><line x1="21" y1="12" x2="9" y2="12" /></svg>
                </button>
              </div>
            )}
          </div>
          <div className="flex flex-wrap gap-3">
            {activeTab !== 'media' && (
              <button
                onClick={() => setShowBulkGen(!showBulkGen)}
                className={`px-5 py-2.5 rounded-xl font-bold shadow-lg transition-all flex items-center gap-2 transform active:scale-95 ${showBulkGen ? 'bg-rose-500 text-white shadow-rose-200' : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'
                  }`}
              >
                <span>{showBulkGen ? 'إلغاء' : '⚡ مولد البرامج'}</span>
              </button>
            )}

            {activeTab === 'posts' && (
              <>
                <button
                  onClick={handleExportPosts}
                  className="px-4 py-2.5 rounded-xl font-bold bg-emerald-50 text-emerald-700 border border-emerald-200 hover:bg-emerald-100 transition-all flex items-center gap-2"
                >
                  <span>📥</span> تصدير JSON
                </button>
                <label className="px-4 py-2.5 rounded-xl font-bold bg-amber-50 text-amber-700 border border-amber-200 hover:bg-amber-100 transition-all flex items-center gap-2 cursor-pointer">
                  <span>📤</span> استيراد JSON
                  <input type="file" accept=".json" onChange={handleImportPosts} className="hidden" />
                </label>
              </>
            )}

            <button
              onClick={() => openNewPostModal()}
              className="bg-indigo-600 text-white px-5 py-2.5 rounded-xl font-bold shadow-lg shadow-indigo-200 hover:bg-indigo-700 transition-all transform hover:-translate-y-0.5 active:translate-y-0 active:scale-95"
            >
              + منشور جديد
            </button>
          </div>
        </header>

        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
          {renderContent()}
        </div>
      </main>

      <PostModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSave={handleSavePost}
        post={editingPost}
        initialDate={initialDate}
        mediaItems={mediaItems}
        onUploadMedia={handleUploadMedia}
      />
    </div>
  );
};

export default App;
