import React, { useState, useEffect } from 'react';
import Sidebar from './components/Sidebar';
import CalendarView from './components/CalendarView';
import GanttChart from './components/GanttChart';
import BulkGenerator from './components/BulkGenerator';
import PostsListView from './components/PostsListView';
import PostModal from './components/PostModal';
import MediaLibrary from './components/MediaLibrary';
import { Post, Campaign, Platform, MediaItem } from './types';
import * as api from './services/api';

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState('calendar');
  const [showBulkGen, setShowBulkGen] = useState(false);
  const [posts, setPosts] = useState<Post[]>([]);
  const [campaigns, setCampaigns] = useState<Campaign[]>([]);
  const [mediaItems, setMediaItems] = useState<MediaItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);

  // Modal State
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingPost, setEditingPost] = useState<Post | null>(null);
  const [initialDate, setInitialDate] = useState<Date | undefined>(undefined);

  // Load data from Supabase on mount
  useEffect(() => {
    const fetchData = async () => {
      setIsLoading(true);
      try {
        const [fetchedPosts, fetchedCampaigns, fetchedMedia] = await Promise.all([
          api.getPosts(),
          api.getCampaigns(),
          api.getMediaItems()
        ]);
        setPosts(fetchedPosts);
        setCampaigns(fetchedCampaigns);
        setMediaItems(fetchedMedia);
      } catch (error) {
        console.error("Failed to fetch data:", error);
        // Fallback or empty state handled by initial state
      } finally {
        setIsLoading(false);
      }
    };
    fetchData();
  }, []);

  const handleBulkPosts = (newPosts: Post[]) => {
    // Save generated posts to DB one by one (or bulk insert if API supported it, here loop for simplicity)
    const savePromises = newPosts.map(p => api.createPost(p));

    Promise.all(savePromises).then((savedPosts) => {
      setPosts(prev => [...prev, ...savedPosts]);

      // If program, create campaign
      if (newPosts.length > 0 && newPosts[0].programId) {
        const prog = newPosts[0];
        const dates = newPosts.map(p => p.date.getTime());
        const minDate = new Date(Math.min(...dates));
        const maxDate = new Date(Math.max(...dates));

        const newCampaign: Campaign = {
          id: '', // Generated by DB
          name: prog.programName || 'برنامج جديد',
          startDate: minDate,
          endDate: maxDate,
          color: '#6366f1',
          description: `برنامج محتوى لـ ${prog.platform} (${newPosts.length} منشور)`
        };

        api.createCampaign(newCampaign).then(savedCampaign => {
          setCampaigns(prev => [savedCampaign, ...prev]);
        });
      }

      alert('تم حفظ البرنامج المولد في قاعدة البيانات بنجاح!');
    }).catch(e => {
      console.error("Failed to save bulk posts", e);
      alert('حدث خطأ أثناء حفظ المنشورات');
    });

    setShowBulkGen(false);
    setActiveTab('posts');
  };

  const deletePost = async (id: string) => {
    if (window.confirm('هل أنت متأكد من حذف هذا المنشور؟')) {
      try {
        await api.deletePost(id);
        setPosts(prev => prev.filter(p => p.id !== id));
      } catch (e) {
        console.error(e);
        alert('فشل الحذف');
      }
    }
  };

  const openNewPostModal = (date?: Date) => {
    setEditingPost(null);
    setInitialDate(date || new Date());
    setIsModalOpen(true);
  };

  const openEditPostModal = (post: Post) => {
    setEditingPost(post);
    setInitialDate(undefined);
    setIsModalOpen(true);
  };

  const handleSavePost = async (post: Post) => {
    try {
      if (post.id && posts.find(p => p.id === post.id)) {
        // Update
        await api.updatePost(post);
        setPosts(prev => prev.map(p => p.id === post.id ? post : p));
      } else {
        // Create (Clean ID if it was a temp local ID during creation, although createPost handles ignoring ID usually or payload doesn't send it if not needed)
        // Actually api.createPost generates new ID.
        // If we passed a dummy ID from modal initialization, api.createPost payload doesn't include ID so it works.
        const savedPost = await api.createPost(post);
        setPosts(prev => [...prev, savedPost]);
      }
      setIsModalOpen(false);
    } catch (e) {
      console.error("Failed to save post", e);
      alert('فشل حفظ المنشور');
    }
  };

  const handleUploadMedia = async (files: FileList) => {
    const file = files[0]; // Simple single file upload for now or loop for multiple
    if (!file) return;

    try {
      // Optimistic UI could be added here
      const savedItem = await api.uploadMediaItem(file);
      setMediaItems(prev => [savedItem, ...prev]);
    } catch (e) {
      console.error("Upload failed", e);
      alert('فشل رفع الملف. تأكد من إعداد Supabase Storage.');
    }
  };

  const handleDeleteMedia = async (id: string) => {
    const item = mediaItems.find(m => m.id === id);
    if (!item) return;

    if (window.confirm('حذف هذه الصورة؟')) {
      try {
        await api.deleteMediaItem(id, item.url);
        setMediaItems(prev => prev.filter(m => m.id !== id));
      } catch (e) {
        console.error(e);
        alert('فشل حذف الصورة');
      }
    }
  };

  const renderContent = () => {
    if (isLoading) {
      return (
        <div className="flex h-64 items-center justify-center">
          <div className="text-gray-400 flex flex-col items-center">
            <div className="w-8 h-8 border-4 border-indigo-200 border-t-indigo-600 rounded-full animate-spin mb-2"></div>
            جاري تحميل البيانات...
          </div>
        </div>
      );
    }

    switch (activeTab) {
      case 'calendar':
        return (
          <div className="space-y-6">
            {showBulkGen && <BulkGenerator onPostsGenerated={handleBulkPosts} />}
            <CalendarView
              posts={posts}
              onAddPost={openNewPostModal}
              onEditPost={openEditPostModal}
            />
          </div>
        );
      case 'gantt':
        return <GanttChart campaigns={campaigns} />;
      case 'posts':
        return (
          <div className="space-y-6">
            {showBulkGen && <BulkGenerator onPostsGenerated={handleBulkPosts} />}
            <PostsListView posts={posts} onDeletePost={deletePost} onEditPost={openEditPostModal} />
          </div>
        );
      case 'media':
        return (
          <MediaLibrary
            mediaItems={mediaItems}
            onUpload={handleUploadMedia}
            onDelete={handleDeleteMedia}
          />
        );
      default:
        return <CalendarView posts={posts} onAddPost={openNewPostModal} onEditPost={openEditPostModal} />;
    }
  };

  return (
    <div className="min-h-screen flex bg-slate-50 font-['IBM_Plex_Sans_Arabic']">
      <Sidebar activeTab={activeTab} setActiveTab={(tab) => { setActiveTab(tab); setShowBulkGen(false); }} />
      <main className="flex-1 mr-64 p-8 transition-all">
        <header className="flex flex-col md:flex-row justify-between items-start md:items-center mb-8 gap-4">
          <div>
            <h2 className="text-3xl font-bold text-gray-900 tracking-tight">
              {activeTab === 'calendar' && 'التقويم الذكي'}
              {activeTab === 'gantt' && 'تخطيط المحتوى'}
              {activeTab === 'posts' && 'أرشيف المحتوى'}
              {activeTab === 'media' && 'مكتبة الوسائط'}
            </h2>
            <p className="text-gray-500 mt-1 font-medium text-sm">نظام إدارة المحتوى المتكامل (Supabase Edition)</p>
          </div>
          <div className="flex flex-wrap gap-3">
            {activeTab !== 'media' && (
              <button
                onClick={() => setShowBulkGen(!showBulkGen)}
                className={`px-5 py-2.5 rounded-xl font-bold shadow-lg transition-all flex items-center gap-2 transform active:scale-95 ${showBulkGen ? 'bg-rose-500 text-white shadow-rose-200' : 'bg-white text-gray-700 border border-gray-200 hover:bg-gray-50'
                  }`}
              >
                <span>{showBulkGen ? 'إلغاء' : '⚡ مولد البرامج'}</span>
              </button>
            )}

            <button
              onClick={() => openNewPostModal()}
              className="bg-indigo-600 text-white px-5 py-2.5 rounded-xl font-bold shadow-lg shadow-indigo-200 hover:bg-indigo-700 transition-all transform hover:-translate-y-0.5 active:translate-y-0 active:scale-95"
            >
              + منشور جديد
            </button>
          </div>
        </header>

        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
          {renderContent()}
        </div>
      </main>

      <PostModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSave={handleSavePost}
        post={editingPost}
        initialDate={initialDate}
        mediaItems={mediaItems}
        onUploadMedia={handleUploadMedia}
      />
    </div>
  );
};

export default App;
